spring:
  application:
    name: exchanger
  datasource:
    url: jdbc:postgresql://localhost:5432/exchanger
    username: exchanger_user
    password: exchanger_pass

  jpa:
    hibernate:
      ddl-auto: update # on prod use only validate

dependencies:
  nbp:
    name: NbpCLient
    url: https://api.nbp.pl
    timeout: PT1S
    max-connections: 10

exchange-rate:
  scheduler:
    timer-rate: "0 30 12 * * MON-FRI"
