wiremock:
  host: http://localhost
  port: 3333

dependencies:
  nbp:
    url: "${wiremock.host}:${wiremock.port}"
    timeout: "100ms"

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop # on prod use only validate