version: '3.1'

services:
  mongodb-service:
    image: mongo:${MONGO_VERSION}
    container_name: mongodb-exchanger
    volumes:
      - mongodata:/data/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: exchanger_user
      MONGO_INITDB_ROOT_PASSWORD: exchanger_pass
      MONGO_INITDB_DATABASE: exchanger
    ports:
      - "27017:27017"

volumes:
  mongodata: