version: '3.1'

services:
  postgresdb-service:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgresdb-exchanger
    volumes:
      - postgresdata:/data/postgresdb
    environment:
      POSTGRES_USER: exchanger_user
      POSTGRES_PASSWORD: exchanger_pass
      POSTGRES_DB: exchanger
    ports:
      - "5432:5432"

volumes:
  postgresdata: